version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:123@db:5432/bookstore?sslmode=disable
    depends_on:
      - db


  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./pkg/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:123@db:5432/bookstore?sslmode=disable", "up"]
    depends_on:
      - db

volumes:
  pgdata: