version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/bookstore?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf # Монтируем кастомный pg_hba.conf

volumes:
  pgdata:
